import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API calls
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 100,
                maxAgeSeconds: 24 * 60 * 60, // 24 hours
            }),
        ],
    })
);

// Cache images
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'image-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
            }),
        ],
    })
);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    console.log('[SW] Push received:', event);

    let data = {};
    try {
        if (event.data) {
            data = event.data.json();
        }
    } catch (err) {
        console.warn('[SW] Push data is not JSON, treating as text');
        data = { title: 'ClassConnect Notification', body: event.data.text() };
    }

    const title = data.title || 'ClassConnect Notification';
    const options = {
        body: data.body || 'You have a new update.',
        icon: data.icon || '/easy-attendance-logo.png',
        badge: data.badge || '/easy-attendance-logo.png',
        vibrate: [100, 50, 100],
        data: {
            url: data.data?.url || data.url || '/'
        },
        actions: [
            { action: 'open', title: 'Open App' },
            { action: 'close', title: 'Close' }
        ],
        tag: data.tag || 'class-connect-notification',
        renotify: true,
        requireInteraction: true // Keeps notification visible until user interacts
    };

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    if (event.action === 'close') return;

    const urlToOpen = event.notification.data.url || '/';

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window open and focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url.includes(urlToOpen) && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
